### ISSUE TITLE
missing required parameter file.

### ISSUE THREAD

**Issue by MohammadHarish52** [adrianhajdin/social_media_app#11]
`export async function createPost(post: INewPost) {
  try {
    //upload image to storage
    const uploadedFile = await uploadFile(post.file[0]);

    if (!uploadedFile) {
      throw Error;
    }
    // Get file url
    const fileUrl = getFilePreview(uploadedFile.$id);

    if (!fileUrl) {
      deleteFile(uploadedFile.$id);
      throw Error;
    }
    // convert tags into an array
    const tags = post.tags?.replace(/ /g, "").split(",") || [];

    // save post to database
    const newPost = await databases.createDocument(
      appwriteConfig.databaseId,
      appwriteConfig.postsCollectionId,
      ID.unique(),
      {
        creator: post.userId,
        caption: post.caption,
        location: post.location,
        imageUrl: fileUrl,
        imageId: uploadedFile?.$id,
        tags: tags,
      }
    );
    if (!newPost) {
      await deleteFile(uploadedFile?.$id);
      throw Error;
    }
    return newPost;
  } catch (error) {
    console.log(error);
  }
### }`

i am recieving this in error

**Comment by MohammadHarish52** [comment]
![Screenshot 2023-11-05 215140](https://github.com/adrianhajdin/social_media_app/assets/109061798/52a99364-bee4-4c6d-b698-bcf20cabd4bd)

**Comment by MohammadHarish52** [comment]
fixed

**Comment by aindriu80** [comment]
what was the fix?
