### ISSUE TITLE
stuck on the create user api

### ISSUE THREAD

**Issue by bullseye405** [adrianhajdin/social_media_app#20]
I am getting error when creating user account

<img width="649" alt="Screenshot 2023-11-16 at 20 25 50" src="https://github.com/adrianhajdin/social_media_app/assets/38998432/ccf643cd-475a-4bac-a573-3afddc086f1d">

All the appwrite configurations are same. Couldn't find out the issue here!
<img width="732" alt="Screenshot 2023-11-16 at 20 27 33" src="https://github.com/adrianhajdin/social_media_app/assets/38998432/4e29cc93-47d4-4ea0-8127-3456e0fc30f5">

<img width="432" alt="Screenshot 2023-11-16 at 20 27 52" src="https://github.com/adrianhajdin/social_media_app/assets/38998432/e7c43d56-4c14-49fb-be0a-8dc65efefe7e">

<img width="598" alt="Screenshot 2023-11-16 at 20 28 08" src="https://github.com/adrianhajdin/social_media_app/assets/38998432/d4720589-3a48-4737-8e6b-12487230bab4">

**Comment by TheerthA88** [comment]
same issue for me as well. couldn't fix it

**Comment by TheerthA88** [comment]
Hey @bullseye405, I've fixed this issue...

**Comment by TheerthA88** [comment]
have you added platform in appwrite?

**Comment by bullseye405** [comment]
@TheerthA88  no, i just followed with the tutorial

**Comment by TheerthA88** [comment]
@bullseye405, it's not there in the tutorial. But we need to add a web platform in appwrite

**Comment by TheerthA88** [comment]
In appwrite, add web platform.

Name: we can give any random (related to project will be looks good)
Hostname: * as in attachment

![appwrite](https://github.com/adrianhajdin/social_media_app/assets/61548780/3b39c325-f94a-4767-9272-03bcf6767530)

**Comment by Swyangdipta** [comment]
> In appwrite, add web platform.
> 
> Name: we can give any random (related to project will be looks good) Hostname: * as in attachment
> 
> ![appwrite](https://user-images.githubusercontent.com/61548780/284292120-3b39c325-f94a-4767-9272-03bcf6767530.png)

thank you it helped

**Comment by gideon-124** [comment]
In appwrite, i have added the web platform. It is not working
![Screenshot from 2023-11-22 19-17-36](https://github.com/adrianhajdin/social_media_app/assets/89646850/43d0a6c4-79f9-49f7-bec0-4124a8859f9b)


can some one help me for this

**Comment by TheerthA88** [comment]
> In appwrite, i have added the web platform. It is not working ![Screenshot from 2023-11-22 19-17-36](https://user-images.githubusercontent.com/89646850/284927109-43d0a6c4-79f9-49f7-bec0-4124a8859f9b.png)
> 
> can some one help me for this

@gideon-124, can you pls share a screenshot of config.ts

**Comment by gideon-124** [comment]
@TheerthA88  
i have shared the screenshots

![Screenshot from 2023-11-23 10-20-58](https://github.com/adrianhajdin/social_media_app/assets/89646850/eeb6f942-2267-4c51-8c38-cb2984db63e5)
![Screenshot from 2023-11-23 10-22-58](https://github.com/adrianhajdin/social_media_app/assets/89646850/9e8b3079-782a-45fb-8c2d-7a16aeb8ad97)
![Screenshot from 2023-11-23 10-26-24](https://github.com/adrianhajdin/social_media_app/assets/89646850/7cf67048-2389-43e3-87bd-bd40516d64f6)
![Screenshot from 2023-11-23 10-26-44](https://github.com/adrianhajdin/social_media_app/assets/89646850/5702ed3b-891c-4475-9d3e-dd50bed9e5ac)

**Comment by TheerthA88** [comment]
> @TheerthA88 i have shared the screenshots
> 
> ![Screenshot from 2023-11-23 10-20-58](https://user-images.githubusercontent.com/89646850/285105482-eeb6f942-2267-4c51-8c38-cb2984db63e5.png) ![Screenshot from 2023-11-23 10-22-58](https://user-images.githubusercontent.com/89646850/285105536-9e8b3079-782a-45fb-8c2d-7a16aeb8ad97.png) ![Screenshot from 2023-11-23 10-26-24](https://user-images.githubusercontent.com/89646850/285105578-7cf67048-2389-43e3-87bd-bd40516d64f6.png) ![Screenshot from 2023-11-23 10-26-44](https://user-images.githubusercontent.com/89646850/285105612-5702ed3b-891c-4475-9d3e-dd50bed9e5ac.png)

@gideon-124, 
remove appwriteConfig.projectId and appwriteConfig.url

In place of those directly give your projectId and url in double quotes
![image](https://github.com/adrianhajdin/social_media_app/assets/61548780/880be546-ddac-444e-928d-f02217567be1)

hope it works :)

**Comment by gideon-124** [comment]
It works fine. Thanks @TheerthA88 

> > @TheerthA88 i have shared the screenshots
> > ![Screenshot from 2023-11-23 10-20-58](https://user-images.githubusercontent.com/89646850/285105482-eeb6f942-2267-4c51-8c38-cb2984db63e5.png) ![Screenshot from 2023-11-23 10-22-58](https://user-images.githubusercontent.com/89646850/285105536-9e8b3079-782a-45fb-8c2d-7a16aeb8ad97.png) ![Screenshot from 2023-11-23 10-26-24](https://user-images.githubusercontent.com/89646850/285105578-7cf67048-2389-43e3-87bd-bd40516d64f6.png) ![Screenshot from 2023-11-23 10-26-44](https://user-images.githubusercontent.com/89646850/285105612-5702ed3b-891c-4475-9d3e-dd50bed9e5ac.png)
> 
> @gideon-124, remove appwriteConfig.projectId and appwriteConfig.url
> 
> In place of those directly give your projectId and url in double quotes ![image](https://user-images.githubusercontent.com/61548780/285184024-880be546-ddac-444e-928d-f02217567be1.png)
> 
> hope it works :)

thanks you. Now it is working fine
