### ISSUE TITLE
The error states "Access to XMLHttpRequest at 'https://cloud.appwrite.io/v1/account' from origin 'http://localhost:5173/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

### ISSUE THREAD

**Issue by samrudh-hashset** [adrianhajdin/social_media_app#54]
I'm getting the CORS policy error despite setting the endpoint to https://cloud.appwrite.io/v1.  Please help.  The error states "Access to XMLHttpRequest at 'https://cloud.appwrite.io/v1/account' from origin 'http://localhost:5173/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
My output:
<img width="1277" alt="Screenshot 2024-04-07 at 4 56 59 AM" src="https://github.com/adrianhajdin/social_media_app/assets/79752299/751aac20-8828-4d1f-9882-1cebea400f1c">
Expected output as shown in the video
<img width="330" alt="Screenshot 2024-04-07 at 5 13 56 AM" src="https://github.com/adrianhajdin/social_media_app/assets/79752299/3b8799c2-8bc1-4295-ab33-76314fd901d2">

**Comment by Murtaza-5253** [comment]
how did you solve it please help

**Comment by samrudh-hashset** [comment]
> how did you solve it please help

check this video out 

https://youtu.be/oEpRh9H5l5g?si=MO4k29ChakH3Nnws
