### ISSUE TITLE
An error regarding imageUrl in api.ts file

### ISSUE THREAD

**Issue by samrudh-hashset** [adrianhajdin/social_media_app#55]
<img width="480" alt="Screenshot 2024-04-08 at 4 27 16 AM" src="https://github.com/adrianhajdin/social_media_app/assets/79752299/b19e3246-7006-482c-9ee3-54f4192b8f25">
<img width="624" alt="Screenshot 2024-04-08 at 4 27 33 AM" src="https://github.com/adrianhajdin/social_media_app/assets/79752299/40d02428-edef-4c2e-95b1-7fc163855896">

As you can see the error is in the imageUrl. I have defined everything as shown in the video and assigned it to type URL. 

The error says "Type 'URL' is missing the following properties from type 'Url': auth, path, slashes, query". What does it mean ?

**Comment by Caesura0** [comment]
What was the solution for this?
