### ISSUE TITLE
"No overload matches this call"

### ISSUE THREAD

**Issue by yang2674** [adrianhajdin/social_media_app#8]
![image](https://github.com/adrianhajdin/social_media_app/assets/94493230/81a1b5dc-ed53-4d9e-8010-9d0a86ce4558)

I'm running into a problem during deployment. I get this `No overload matches this call` error. 

[Found this.](https://bobbyhadz.com/blog/typescript-no-overload-matches-this-call)

It says I'm passing a parameter that doesn't match the specified overloads.

Thing is, my code is identical to the finished project.

**Comment by fuzanu** [comment]
it's because of tanstack query v5, use this code instead:

export const useGetPosts = () => {
  return useInfiniteQuery({
    queryKey: [QUERY_KEYS.GET_INFINITE_POSTS],
    queryFn: getInfinitePosts as any,
    initialPageParam: 0,
    getNextPageParam: (lastPage: any) => {
      // If there's no data, there are no more pages.
      if (lastPage && lastPage.documents.length === 0) {
        return null;
      }

      // Use the $id of the last document as the cursor.
      const lastId = lastPage.documents[lastPage.documents.length - 1].$id;
      return lastId;
    },
  });
};

**Comment by yang2674** [comment]
Thanks for the reply. I actually figured out it was due to `initialPageParam: 0`

I was able to get it working, thanks!

**Comment by RandeepSingh72** [comment]
> it's because of tanstack query v5, use this code instead:
> 
> export const useGetPosts = () => { return useInfiniteQuery({ queryKey: [QUERY_KEYS.GET_INFINITE_POSTS], queryFn: getInfinitePosts as any, initialPageParam: 0, getNextPageParam: (lastPage: any) => { if (lastPage && lastPage.documents.length === 0) { return null; }
> 
> ```
>   const lastId = lastPage.documents[lastPage.documents.length - 1].$id;
>   return lastId;
> },
> ```
> 
> }); };

thanks bro

**Comment by iMo7y** [comment]
Your a legend fuzanu had the same issue
